### ISSUE TITLE
Switch to JavaScript

### ISSUE THREAD

**Issue by edahlseng** [jneuendorf/code-annotations#20]
I know this suggestion is going to be controversial. But at least hear me out for a second... I think that CoffeeScript can alienate a lot of potential contributors, and has downsides of its own. Meanwhile, JavaScript has improved a lot in recent years, and with a good linter it can avoid most of the issues that CoffeeScript aims to fix. The alienation of potential contributors is the biggest factor, I think, and the main reason I propose this switch.

**Comment by jneuendorf** [comment]
Just today, I though about switching to JS myself. I also find that the ecosystem has improved with it (babel, eslint). But I haven't though about CoffeeScript preventing others to contribute - that's a good point.
As you would like to contribute to #18 do you prefer switching to JS before starting to work on the issue?

**Comment by edahlseng** [comment]
Sure, can do!

**Comment by jneuendorf** [comment]
I created an `es6` branch (https://github.com/jneuendorf/code-annotations/tree/es6) and added you as collaborator. So if you wanna join porting CoffeeScript to ES6 you should be able to join 😉

**Comment by edahlseng** [comment]
Sounds great! I'll add in what I currently have a little later tonight. Got everything converted, but chasing a few bugs

**Comment by jneuendorf** [comment]
Oh alright. That was quick 😄
I just pushed something...hope there aren't too difficult conflicts.

**Comment by edahlseng** [comment]
Okay, I just pushed what I had. The package starts up successfully, but still crashes whenever trying to do anything. The current bug that I'm focusing on is crashing while trying to render existing annotations. It looks like the problem is that renderers aren't being properly registered, because they don't exist in the atom.config file. I'm not sure when/where the defaults are written for that config... any thoughts?

**Comment by jneuendorf** [comment]
I fixed some stuff. Now the gutter icons behave like before. See https://github.com/jneuendorf/code-annotations/commit/eb481ab7f6cd78e4dacfad6e0b3c45ab1e9e4601.

**Comment by edahlseng** [comment]
Woot! It looks like adding annotations also work as previously. A bit more testing is probably needed, but I haven't found any more bugs yet.

**Comment by jneuendorf** [comment]
Sounds great! I will close this issue once the last couple of CoffeeScript leftovers (i.e. `for` loops, default parameters) are gone and the linter is happy.

**Comment by jneuendorf** [comment]
I am done for my part. But some more testing is needed I guess.
Closing this for now.
