### ISSUE TITLE
Uncaught Error: The editor with path ...

### ISSUE THREAD

**Issue by bradleyDean** [jneuendorf/code-annotations#23]
[Enter steps to reproduce:]

1..ctrl-alt-c (twice, as described in README)
2. selected "Add annotation with file", then entered name of new annotation
3. Clicked "ok" in "Select Asset" popup.
3. Used file browser (Gonme, Ubuntu 16. to pick .png file to use for annotation.
4. Got errors in atom. Pluging seems to have crashed.

Is it deprecated?

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Ubuntu 16.04.4
**Thrown From**: [code-annotations](https://github.com/jneuendorf/code-annotations) package 2.1.3

### Stack Trace

Uncaught Error: The editor with path '/home/brad/Desktop/Dev/Ionic2/gymappionic2remote/src/providers/feed-buffer/feed-buffer.ts' has not been initialized but it should. Please report this bug!

```
At /home/brad/.atom/packages/code-annotations/lib/annotation-manager.coffee:492

Error: The editor with path '/home/brad/Desktop/Dev/Ionic2/gymappionic2remote/src/providers/feed-buffer/feed-buffer.ts' has not been initialized but it should. Please report this bug!
    at Object._createNewAnnotation (/packages/code-annotations/lib/annotation-manager.coffee:492:19)
    at Object.addAnnotationWithFile (/packages/code-annotations/lib/annotation-manager.coffee:124:23)
    at CodeAnnotationNameDialog.onSubmitCallback (/packages/code-annotations/lib/annotation-manager.coffee:114:22)
    at CodeAnnotationNameDialog.module.exports.CodeAnnotationNameDialog._submit (/packages/code-annotations/lib/views/asset-name-dialog.coffee:14:22)
    at /packages/code-annotations/lib/views/dialog.coffee:20:25)
    at CommandRegistry.handleCommandEvent (/snap/atom/141/usr/share/atom/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/snap/atom/141/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/snap/atom/141/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/snap/atom/141/usr/share/atom/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -8:08.5.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -8:07.9.0 intentions:highlight (input.hidden-input)
     -8:07.5.0 core:save (input.hidden-input)
  2x -8:00.5.0 intentions:highlight (input.hidden-input)
  2x -3:41.8.0 tree-view:toggle (input.hidden-input)
     -3:38.3.0 intentions:highlight (input.hidden-input)
     -3:38.1.0 bracket-matcher:go-to-matching-bracket (input.hidden-input)
     -3:36.4.0 intentions:highlight (input.hidden-input)
     -3:36.2.0 settings-view:open (input.hidden-input)
     -3:30.3.0 core:confirm (input.hidden-input)
 23x -3:26.2.0 core:backspace (input.hidden-input)
     -3:01.3.0 core:confirm (input.hidden-input)
     -1:04.2.0 code-annotations:show-commands (input.hidden-input)
     -0:51.7.0 code-annotations:add-annotation-with-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.has-code-annotations-container)
     -0:44.5.0 core:backspace (input.hidden-input)
     -0:39.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-beautify 0.32.2 
atom-ctags 5.1.2 
atom-typescript 12.3.8 
atom-updater-linux 1.0.6 
autocomplete-ionic-framework 0.2.2 
autocomplete-ionic2-framework 0.3.2 
busy-signal 1.4.3 
code-annotations 2.1.3 
color-picker 2.2.5 
emmet 2.4.3 
goto-definition 1.3.4 
intentions 1.1.5 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-ui-default 1.7.1 
minimap-find-and-replace 4.5.2 
symbol-gen 1.3.1 
symbols-tree-view 0.14.0 
sync-settings 0.8.5 
tab-to-escape 0.1.0 
teletype 0.10.0 
todo-show 2.1.0 
unsaved-changes 0.1.0 
vim-mode-plus 1.31.1 
vim-surround 0.8.1 
wakatime 7.0.4 
```

**Comment by jneuendorf** [comment]
Hey, thanks for the report.
I can reproduce the error. It occurs when a grammar is not supported - in this case TypeScript.

This problem will disappear with [v3](https://github.com/jneuendorf/code-annotations/milestone/1) which I am currently working on.
I'll try to release an update with support for TypeScript in the mean time though.

**Comment by bradleyDean** [comment]
Thanks!

**Comment by jneuendorf** [comment]
Check out v2.2.0
I hope it fixes your problem 😉

**Comment by bradleyDean** [comment]
Thanks, I'll check it out soon.
BTW, this package is brilliant. I can't believe I've lived without
something like this for so long.

It would be cool to make a little code annotation app. I'm brain storming
ways to snap a photo of hand-drawn diagrams/notes and have the app send the
annotation to the correct file and line number.

Thanks again!

**Comment by bradleyDean** [comment]
...if you like the app idea, I'm currently working on an ionic 3 app and
would be happy to pitch in.

**Comment by jneuendorf** [comment]
Hey,

I'm glad you like the package. Leave a star if you like 😉 

The app idea is pretty cool. I've created an issue for discussion: #24.
Implementation is postponed until `code-annotations@3` is done.

**Comment by jneuendorf** [comment]
I assume the problem was solved. Feel free to reopen this issue.

**Comment by jneuendorf** [comment]
@bradleyDean FYI, I have created a React Native app which works on iOS 11 :)
